### ISSUE TITLE
3.3V / 5V

### ISSUE THREAD

**Issue by arthurwolf** [Bouni/smoothieboard-graphics#1]
Hey there.

Again, thanks a lot for these, they have been very useful, and will be used more ( I'm preparing a video series that uses them too ).

In these : http://smoothieware.org/pinout , the power for the endstops, and the power for the serial, says 3.3V, but it's actually 5V. So I opened an issue :)

Cheers !!!

**Comment by Bouni** [comment]
Will fix that as soon as possible :-)

**Comment by Bouni** [comment]
Fixed the wrong labels for both graphics

**Comment by arthurwolf** [comment]
Yay ! And it auto-updated on the wiki, perfect !
Thanks a lot :)

On Mon, Sep 28, 2015 at 9:19 AM, bouni notifications@github.com wrote:

> Fixed the wrong labels for both graphics
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Bouni/smoothieboard-graphics/issues/1#issuecomment-143658502
> .

## 

Courage et bonne humeur.
